Repository proRamLOGO/quantum-algorithms, pull requests merged in 2021-02, with the labels that each got.

#16 Updated README.md
  README.md
Labels: CrossWoC, documentation, good first issue

#18 Add Deutsch Josza Code + Readme Documentation | Qiskit
  Qiskit/Deutsch Josza Algorithm/Deutsch Josza Algorithm.ipynb
  Qiskit/Deutsch Josza Algorithm/README.md
Labels: CrossWoC, easy

#19 Add CHSH Code + Readme Documentation | Qiskit
  Qiskit/CHSH Implementation/CHSH Game.ipynb
  Qiskit/CHSH Implementation/README.md
Labels: CrossWoC, easy

#28 Add QAOA Algorithm + Readme | Qiskit
  Qiskit/QAOA(Quantum Approximate Optimization Algorithm)/QAOA.ipynb
  Qiskit/QAOA(Quantum Approximate Optimization Algorithm)/README.md
Labels: CrossWoC, easy

#26 Add QGANs Implementation + Readme | Qiskit
  Qiskit/QGANs(Quantum Generative Adversarial Networks)/QGANs.ipynb
  Qiskit/QGANs(Quantum Generative Adversarial Networks)/README.md
Labels: CrossWoC, easy

#25 Add Continuous + Discrete Random Walks Algorithms Code + Documentation
  Qiskit/Quantum Random Walks/ContinuousTimeQuantumWalks.ipynb
  Qiskit/Quantum Random Walks/DiscreteTimeQuantumWalk.ipynb
  Qiskit/Quantum Random Walks/README.md
  Qiskit/Quantum Random Walks/assets/Discrete Walk Asset.png
Labels: CrossWoC, medium

#27 Add QSVM Code + Readme | Qiskit
  Qiskit/QSVM(Quantum Support Vector Machines)/QSVM.ipynb
  Qiskit/QSVM(Quantum Support Vector Machines)/README.md
Labels: CrossWoC, easy
